obmcutil: Add wait/timeout option
The option to block/wait for a state transition to complete has
been added. The transition is expected to occur within a set
timeout window and will terminate if the desired state has not
been observed within that window. It may be possible for the
state transition to complete outside this window, but it is
assumed to be a failure.

Change-Id: Icb9ff29f51b8712469fd9957b7e4b287704cb314
Signed-off-by: Anthony Wilson <wilsonan@us.ibm.com>

diff --git a/obmcutil b/obmcutil
--- a/obmcutil
+++ b/obmcutil
@@ -5,7 +5,7 @@ set -euo pipefail
 OPTS="bmcstate,bootprogress,chassisoff,chassison,chassisstate,hoststate,\
 power,poweroff,poweron,state,status"
 
-USAGE="Usage: obmcutil [-h]
+USAGE="Usage: obmcutil [-h] [--wait]
                 {$OPTS}"
 
 INTERFACE_ROOT=xyz.openbmc_project
@@ -23,17 +23,82 @@ print_help ()
     echo ""
     echo "optional arguments:"
     echo "  -h, --help          show this help message and exit"
+    echo "  -w, --wait          block until state transition succeeds or fails"
     exit 0
+}
+
+run_timeout ()
+{
+    local timeout="$1"; shift
+    local cmd="$@"
+
+    case $VALUE in
+        ${STATE_INTERFACE}.Host.Transition.On)
+            query="hoststate"
+            expected_state=${STATE_INTERFACE}.Host.HostState.Running
+            ;;
+        ${STATE_INTERFACE}.Host.Transition.Off)
+            query="hoststate"
+            expected_state=${STATE_INTERFACE}.Host.HostState.Off
+            ;;
+        ${STATE_INTERFACE}.Chassis.Transition.On)
+            query="chassisstate"
+            expected_state=${STATE_INTERFACE}.Chassis.PowerState.On
+            ;;
+        ${STATE_INTERFACE}.Chassis.Transition.Off)
+            query="chassisstate"
+            expected_state=${STATE_INTERFACE}.Chassis.PowerState.Off
+            ;;
+    esac
+    
+    $cmd
+
+    # Run a background query for the transition to the expected state
+    # This will be killed if the transition doesn't succeed within
+    # a timeout period.
+    (
+        while ! grep -q $expected_state <<< $(handle_cmd $query) ; do
+            sleep 1
+        done
+    ) &
+    child=$!
+
+    # Could be bad if process is killed before 'timeout' occurs if
+    # transition doesn't succeed.
+    trap -- "" SIGTERM
+
+    # Workaround for lack of 'timeout' command.
+    (
+        sleep $timeout
+        kill $child
+    ) > /dev/null 2>&1 &
+
+    if ! wait $child; then
+        echo "Unable to confirm '$ROOT_COMMAND' success" \
+        "within timeout period (${timeout}s)"
+    fi
+}
+
+run_cmd ()
+{
+    local cmd="$@";
+
+    if [ -n "$WAIT" ]; then
+        run_timeout $WAIT "$cmd"
+    else
+        $cmd
+    fi
 }
 
 set_property ()
 {
-    busctl set-property "$@"
+    run_cmd busctl set-property "$@"
 }
 
 get_property ()
 {
-    busctl get-property "$@"
+    WAIT=""
+    run_cmd busctl get-property "$@"
 }
 
 state_query ()
@@ -141,6 +206,10 @@ handle_cmd ()
 
 for arg in "$@"; do
     case $arg in
+        -w|--wait)
+            WAIT=30
+            continue
+            ;;
         -h|--help)
             print_help
             ;;
@@ -148,6 +217,7 @@ for arg in "$@"; do
             print_err "Unknown option: $arg"
             ;;
         *)
+            ROOT_COMMAND=$arg
             handle_cmd $arg
             break
             ;;
