obmcutil: Add chassiskill option
Change-Id: I9b8289e433bfcf918d430c012ec8879b58e523b0
Signed-off-by: Anthony Wilson <wilsonan@us.ibm.com>

diff --git a/obmcutil b/obmcutil
--- a/obmcutil
+++ b/obmcutil
@@ -2,7 +2,7 @@
 
 set -euo pipefail
 
-OPTS="bmcstate,bootprogress,chassisoff,chassison,chassisstate,hoststate,\
+OPTS="bmcstate,bootprogress,chassiskill,chassisoff,chassison,chassisstate,hoststate,\
 power,poweroff,poweron,state,status"
 
 USAGE="Usage: obmcutil [-h] [--wait]
@@ -42,6 +42,18 @@ print_help ()
     echo "  -h, --help          show this help message and exit"
     echo "  -w, --wait          block until state transition succeeds or fails"
     exit 0
+}
+
+run_chassiskill ()
+{
+    local out=$(/usr/libexec/chassiskill 2>&1)
+    local rc=$?
+
+    if ! $rc ; then
+        echo "Error: failed to run chassiskill"
+        echo "$out"
+        exit $rc
+    fi
 }
 
 run_timeout ()
@@ -203,6 +215,9 @@ handle_cmd ()
                     | sed 's/i[ ^I]*//')
                 printf "%s = %s\n" $property $STATE
             done
+            ;;
+        chassiskill)
+            run_chassiskill
             ;;
         *)
             print_usage_err "Invalid command '$1'"
