boot-block: inform user if blocking error present
If a boot blocking error is present then be sure the user is notified
when try a boot operation.

Tested:
root@witherspoon:~# obmcutil poweron
!!!!!!!!!!
WARNING! System has blocking errors that will prevent boot
Blocking Error: /xyz/openbmc_project/logging/entry/21
Blocking Error: /xyz/openbmc_project/logging/entry/24
!!!!!!!!!!

Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
Change-Id: Id856c809e4cd6b6d0621d682d29aec8d72f4b563

diff --git a/obmcutil b/obmcutil
--- a/obmcutil
+++ b/obmcutil
@@ -224,6 +224,18 @@ check_boot_block_errors ()
     done
 }
 
+# helper function to check for boot block errors and notify user
+check_and_warn_boot_block()
+{
+    blockingErrors=$(check_boot_block_errors)
+    if ! [ -z "$blockingErrors" ]; then
+        echo !!!!!!!!!!
+        echo "WARNING! System has blocking errors that will prevent boot"
+        echo "$blockingErrors"
+        echo !!!!!!!!!!
+    fi
+}
+
 handle_cmd ()
 {
     case "$1" in
@@ -238,6 +250,7 @@ handle_cmd ()
             set_property $SERVICE $OBJECT $INTERFACE $PROPERTY "s" $VALUE
             ;;
         chassison)
+            check_and_warn_boot_block
             OBJECT=$STATE_OBJECT/chassis0
             SERVICE=$(mapper get-service $OBJECT)
             INTERFACE=$STATE_INTERFACE.Chassis
@@ -258,6 +271,7 @@ handle_cmd ()
             set_property $SERVICE $OBJECT $INTERFACE $PROPERTY "s" $VALUE
             ;;
         poweron)
+            check_and_warn_boot_block
             OBJECT=$STATE_OBJECT/host0
             SERVICE=$(mapper get-service $OBJECT)
             INTERFACE=$STATE_INTERFACE.Host
@@ -300,6 +314,7 @@ handle_cmd ()
             do
                 handle_cmd $query
             done
+            check_and_warn_boot_block
             ;;
         bootprogress)
             OBJECT=$STATE_OBJECT/host0
