obmcutil: Add wait/timeout option
The option to block/wait for a state transition to complete has
been added. The transition is expected to occur within a set
timeout window and will terminate if the desired state has not
been observed within that window. It may be possible for the
state transition to complete outside this window, but it is
assumed to be a failure.

Change-Id: Icb9ff29f51b8712469fd9957b7e4b287704cb314
Signed-off-by: Anthony Wilson <wilsonan@us.ibm.com>

diff --git a/obmcutil b/obmcutil
--- a/obmcutil
+++ b/obmcutil
@@ -3,7 +3,7 @@
 OPTS="bmcstate,bootprogress,chassisoff,chassison,chassisstate,hoststate,\
 power,poweroff,poweron,state,status"
 
-USAGE="Usage: obmcutil [-h]
+USAGE="Usage: obmcutil [-h] [--wait]
                 {$OPTS}"
 
 INTERFACE_ROOT=xyz.openbmc_project
@@ -21,12 +21,88 @@ print_help ()
     echo ""
     echo "optional arguments:"
     echo "  -h, --help          show this help message and exit"
+    echo "  -w, --wait          block until state transition succeeds or fails"
     exit 0
+}
+
+run_timeout ()
+{
+    local cmd="$1";
+    local timeout="$2";
+
+    if [[ $VALUE = "$STATE_INTERFACE.Host"* ]]; then
+        query="hoststate"
+        if [[ $VALUE = *"On" ]]; then
+            expected_state="$STATE_INTERFACE.Host.HostState.Running"
+        else
+            expected_state="$STATE_INTERFACE.Host.HostState.Off"
+        fi
+    elif [[ $VALUE = "$STATE_INTERFACE.Chassis"* ]]; then
+        query="chassisstate"
+        if [[ $VALUE = *".On" ]]; then
+            expected_state="$STATE_INTERFACE.Chassis.PowerState.On"
+        else
+            expected_state="$STATE_INTERFACE.Chassis.PowerState.Off"
+        fi
+    else
+        # Should never hit this, more of a debug case...
+        echo "Unable to match value: $VALUE"
+    fi
+
+    eval "$cmd"
+
+    # Run a background query for the transition to the expected state
+    # This will be killed if the transition doesn't succeed within
+    # a timeout period.
+    (
+        while : ; do
+            local state=$(handle_arg $query)
+            if grep -q $expected_state <<< "$state"; then
+                break
+            fi
+        done
+    ) &
+    child=$!
+
+    # Could be bad if process is killed before 'timeout' occurs if
+    # transition doesn't succeed.
+    trap -- "" SIGTERM
+
+    # To check if the command was killed from time out.
+    set +e
+
+    # Workaround for lack of 'timeout' command.
+    (
+        sleep $timeout
+        kill $child
+    ) > /dev/null 2>&1 &
+
+    wait $child
+
+    rc=$?
+    if [[ $rc != 0 ]]; then
+        echo "Unable to confirm '$ROOT_COMMAND' success" \
+        "within timeout period (${timeout}s)"
+    fi
+
+    set -e
+}
+
+run_cmd ()
+{
+    local cmd="$@";
+
+    if [ "$WAIT" == "y" ]; then
+        local timeout=30
+        run_timeout "$cmd" $timeout
+    else
+        eval $cmd
+    fi
 }
 
 call ()
 {
-    busctl "$@"
+    run_cmd 'busctl' "$@"
 }
 
 set_property ()
@@ -36,6 +112,7 @@ set_property ()
 
 get_property ()
 {
+    WAIT="n"
     call 'get-property' "$@"
 }
 
@@ -144,6 +221,10 @@ handle_arg ()
 
 for arg in "$@"; do
     case $arg in
+        -w|--wait)
+            WAIT=y
+            continue
+            ;;
         -h|--help)
             print_help
             ;;
@@ -151,6 +232,7 @@ for arg in "$@"; do
             print_err "Unknown option: $1"
             ;;
         *)
+            ROOT_COMMAND=$arg
             handle_arg $arg
             break
             ;;
